### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fxdave** [mechpen/rterm#7]
What license did you publish this software under?
I guess I am able to fork it as it is following the suckless' st, but I'm currently licensing all my repositories under GPLv2 or 3, and I don't know whether I can do that with my fork or not.

**Comment by mechpen** [comment]
I am using "MIT OR Apache-2.0". So I guess you could re-licensing?

**Comment by fxdave** [comment]
I keep it then. Thanks for letting me know.
